image = "/iopsstor/scratch/cscs/lukasd/enroot/lukasgd+ngc-fcn+24.01.sqsh"

mounts = [
        "/iopsstor/scratch/cscs:/iopsstor/scratch/cscs",
        "/users/lukasd/.vscode-server:/users/lukasd/.vscode-server",
        "/users/lukasd/.wget-hsts:/users/lukasd/.wget-hsts"
]

workdir = "/iopsstor/scratch/cscs/lukasd/llm/sc23-dl-tutorial"

writable = true

[env]
NCCL_DEBUG = "WARN"

# Enable the aws-ofi-nccl hook to use slingshot
[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

# if uncommented must use --pty with srun
[annotations.com.hooks.ssh]
enabled = "true"
authorize_ssh_key = "/users/lukasd/.ssh/cscs-key.pub"
